version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    restart: always
    # ports:
    #   - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orange315
    command: --innodb-buffer-pool-size=2G --max-connections=1000
    volumes:
      - mariadb_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    # ports:
    #   - "6379:6379"
    volumes:
      - redis_data:/data

  python-service:
    build:
      context: ./python-service
      dockerfile: Dockerfile
    container_name: python
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql+aiomysql://root:root@10.88.0.2:3306/orange315
      REDIS_URL: redis://10.88.0.3:6379/0
    depends_on:
      - mariadb
      - redis

volumes:
  mariadb_data:
  redis_data:
