-- wrk Lua script for testing Variant Z flash sale orders
-- Usage: wrk -t12 -c50 -d10s -s wrk_order_script.lua http://localhost:30017/api/v1/orders
--
-- This script reads SKU IDs from /tmp/stress_test_sku_ids.txt (generated by setup_test_data.py)
-- and sends order requests for flash sale products.

-- Load SKU IDs from file
local sku_ids = {}
local file = io.open("/tmp/stress_test_sku_ids.txt", "r")
if file then
    for line in file:lines() do
        local trimmed = line:gsub("^%s*(.-)%s*$", "%1")
        if trimmed ~= "" then
            table.insert(sku_ids, trimmed)
        end
    end
    file:close()
else
    print("ERROR: Could not open /tmp/stress_test_sku_ids.txt")
    print("Please run: docker exec flash-python-z python /app/setup_test_data.py")
    os.exit(1)
end

-- Verify we have SKU IDs
if #sku_ids == 0 then
    print("ERROR: No SKU IDs found in /tmp/stress_test_sku_ids.txt")
    print("Please run: docker exec flash-python-z python /app/setup_test_data.py")
    os.exit(1)
end

print(string.format("Loaded %d SKU IDs for flash sale testing", #sku_ids))

-- Counter for generating unique emails
local counter = 0

-- Setup method and headers
wrk.method = "POST"
wrk.headers["Content-Type"] = "application/json"
wrk.headers["Accept"] = "application/json"

-- Request function - called for each request
request = function()
    counter = counter + 1

    -- Select a SKU (for single SKU, always use first; for multiple, randomize)
    local sku_id
    if #sku_ids == 1 then
        sku_id = sku_ids[1]
    else
        sku_id = sku_ids[math.random(1, #sku_ids)]
    end

    -- Unique email for each request
    local thread_id = wrk.thread:get("id") or 0
    local email = string.format("stress-test-%d-%d@example.com", thread_id, counter)

    -- JSON request body
    local body = string.format([[{
        "customer_email": "%s",
        "customer_name": "Stress Test User %d",
        "line_items": [
            {
                "sku_id": "%s",
                "quantity": 1
            }
        ],
        "currency": "USD"
    }]], email, counter, sku_id)

    return wrk.format("POST", nil, nil, body)
end

-- Initialize thread with counters
function setup(thread)
    thread:set("id", math.random(1, 10000))
end

-- Statistics tracking
local success_count = 0
local error_count = 0
local sold_out_count = 0
local insufficient_stock_count = 0

function init(args)
    success_count = 0
    error_count = 0
    sold_out_count = 0
    insufficient_stock_count = 0
end

-- Response function - track errors by type
response = function(status, headers, body)
    if status == 201 then
        success_count = success_count + 1
    elseif status == 400 then
        if body and (body:find("sold out") or body:find("TOKEN_NOT_AVAILABLE") or body:find("SOLD_OUT")) then
            sold_out_count = sold_out_count + 1
        elseif body and (body:find("INSUFFICIENT_STOCK") or body:find("insufficient stock")) then
            insufficient_stock_count = insufficient_stock_count + 1
        else
            error_count = error_count + 1
        end
    else
        error_count = error_count + 1
    end
end

-- Done function - print summary
done = function(summary, latency, requests)
    io.write("\n")
    io.write("════════════════════════════════════════════════════════════════\n")
    io.write("     VARIANT Z FLASH SALE ORDER BENCHMARK RESULTS\n")
    io.write("════════════════════════════════════════════════════════════════\n")
    io.write(string.format("  Total Requests:     %d\n", summary.requests))
    io.write(string.format("  Success (201):      %d\n", success_count))
    io.write(string.format("  Sold Out:           %d\n", sold_out_count))
    io.write(string.format("  Insufficient Stock: %d\n", insufficient_stock_count))
    io.write(string.format("  Other Errors:       %d\n", error_count))
    io.write("────────────────────────────────────────────────────────────────\n")
    io.write(string.format("  Requests/sec:       %.2f\n", summary.requests / summary.duration * 1000000))
    io.write(string.format("  Transfer/sec:       %.2f KB\n", summary.bytes / summary.duration * 1000000 / 1024))
    io.write("────────────────────────────────────────────────────────────────\n")
    io.write("  Latency Distribution:\n")
    io.write(string.format("    50%%:              %.2f ms\n", latency:percentile(50) / 1000))
    io.write(string.format("    75%%:              %.2f ms\n", latency:percentile(75) / 1000))
    io.write(string.format("    90%%:              %.2f ms\n", latency:percentile(90) / 1000))
    io.write(string.format("    99%%:              %.2f ms\n", latency:percentile(99) / 1000))
    io.write("════════════════════════════════════════════════════════════════\n")
end
